use_frameworks!

platform :ios, '11.0'

target 'ODREurobet_Example' do
  pod 'ODREurobet', :path => '../'

#  pod 'SSZipArchive'
#  pod 'GCDWebServer', '3.5.3'
#  pod 'React-Core', :path => '../node_modules/react-native/'
  
  target 'ODREurobet_Tests' do
    inherit! :search_paths

    
  end
end
